Code-Challenge/Models/Employee.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EmployeeManagement.Models
{
    [Table("tblEmployee")]
    public class Employee
    {
        public int EmployeeId { get; set; }

        [Required]
        [MaxLength(50, ErrorMessage = "First Name cannot exceed 50 characters")]
        [Display(Name = "First Name")]
        public string FirstName { get; set; }

        [Required]
        [MaxLength(50, ErrorMessage = "Last Name cannot exceed 50 characters")]
        [Display(Name = "Last Name")]
        public string LastName { get; set; }

        public ICollection<Dependent> Dependents { get; set; }
    }
}

Code-Challenge/Controllers/DependentController.cs
using EmployeeManagement.Common;
using EmployeeManagement.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;

namespace EmployeeManagement.Controllers
{
    [Authorize]
    public class DependentController : Controller
    {
        private readonly IDependentRepository _dependentRepository;

        public DependentController(IDependentRepository dependentRepository)
        {
            _dependentRepository = dependentRepository;
        }

        [HttpGet]
        //Index action method to retrive all dependents
        public IActionResult Index()
        {
            try
            {
                IEnumerable<Dependent> dependents = _dependentRepository.GetAllDependents();
                return View(dependents);
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Error");
            }

        }

        [HttpGet]
        //create dependent get action
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken()]
        //create dependent post action
        public IActionResult AddDependent(Dependent dependent)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    Dependent newDependent = _dependentRepository.AddDependent(dependent);
                    return RedirectToAction("Details", "employee", new { id = newDependent.EmployeeId });
                }
                catch (Exception)
                {
                    return RedirectToAction("Error", "Error");
                }
            }
            return View();
        }

        [HttpGet]
        //edit existing dependent action
        public IActionResult EditDependent(int id)
        {
            try
            {
                Dependent dependent = _dependentRepository.GetDependentById(id);
                if (dependent == null)
                {
                    ViewBag.ErrorMessage = $"Dependent with Id = {id} not found.";
                    return View("DependentNotFound", id);
                }
                return View(dependent);
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Error");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken()]
        //Method to edit/update dependent
        public IActionResult EditDependent(Dependent updatedependent)
        {
            if (ModelState.IsValid)
            {
                //check valid firstname
                if (!string.IsNullOrWhiteSpace(updatedependent?.FirstName) && !General.RegexPatterns.IsStringOnlyAlphaNumeric(updatedependent?.FirstName?.Trim()))
                {
                    ViewBag.ErrorMessage = $"Please enter valid Dependent FirstName = {updatedependent.FirstName} Accepts only AlphaNumeric";
                    return View(updatedependent);
                }

                //check valid lastname
                if (!string.IsNullOrWhiteSpace(updatedependent?.LastName) && !General.RegexPatterns.IsStringOnlyAlphaNumeric(updatedependent?.LastName?.Trim()))
                {
                    ViewBag.ErrorMessage = $"Please enter valid Dependent LastName = {updatedependent.LastName} Accepts only AlphaNumeric";
                    return View(updatedependent);
                }

                try
                {
                    if (updatedependent?.DependentId != null)
                    {
                        _dependentRepository.UpdateDependent(updatedependent);
                        return RedirectToAction("Details", "employee", new { id = updatedependent.EmployeeId });
                    }
                }
                catch (Exception)
                {
                    return RedirectToAction("Error", "Error");
                }
            }
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken()]
        //Method to delete dependent
        public IActionResult DeleteDependent(int id)
        {
            try
            {
                //get dependent by dependent id
                Dependent dependent = _dependentRepository.GetDependentById(id);
                //check dependent exists or not
                if (dependent != null)
                {
                    //delete dependent from database
                    _dependentRepository.DeleteDependent(id);
                    return RedirectToAction("Details", "employee", new { id = dependent.EmployeeId });
                }
                return View();
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Error");
            }
        }

    }
}

Code-Challenge/Controllers/EmployeeController.cs
using EmployeeManagement.Common;
using EmployeeManagement.Models;
using EmployeeManagement.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;

namespace EmployeeManagement.Controllers
{
    //Employee Controller
    [Authorize]
    public class EmployeeController : Controller
    {
        private readonly IEmployeeRepository _employeeRepository;
        private readonly IDependentRepository _dependentRepository;


        //Employee controller constructor
        public EmployeeController(IEmployeeRepository employeeRepository, IDependentRepository dependentRepository)
        {
            _employeeRepository = employeeRepository;
            _dependentRepository = dependentRepository;
        }

        //Get All employees List
        [HttpGet]
        public IActionResult EmployeeList()
        {
            IEnumerable<Employee> employees = _employeeRepository.GetAllEmployees();
            EmployeesListViewModel employeesListViewModel = new EmployeesListViewModel()
            {
                Employees = employees
            };
            return View(employeesListViewModel);
        }

        [HttpGet]
        public IActionResult Search(string SearchTerm)
        {
            IEnumerable<Employee> employees = _employeeRepository.Search(SearchTerm);
            EmployeesListViewModel employeesListViewModel = new EmployeesListViewModel()
            {
                Employees = employees
            };
            return View("EmployeeList", employeesListViewModel);
        }

        //return create an employee view
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        //Add an employee by employee object
        [HttpPost]
        [ValidateAntiForgeryToken()]
        public IActionResult Create(Employee employee)
        {
            if (ModelState.IsValid)
            {
                //check valid firstname
                if (!string.IsNullOrWhiteSpace(employee?.FirstName) && !General.RegexPatterns.IsStringOnlyAlphaNumeric(employee?.FirstName?.Trim()))
                {
                    ViewBag.ErrorMessage = $"Please enter valid Employee FirstName = {employee.FirstName} Accepts only AlphaNumeric";
                    return View();
                }

                //check valid lastname
                if (!string.IsNullOrWhiteSpace(employee?.LastName) && !General.RegexPatterns.IsStringOnlyAlphaNumeric(employee?.LastName?.Trim()))
                {
                    ViewBag.ErrorMessage = $"Please enter valid Employee LastName = {employee.LastName} Accepts only AlphaNumeric";
                    return View();
                }

                //check employee already exists
                if (IsEmployeeExists(employee))
                {
                    ViewBag.ErrorMessage = $"Employee with FirstName = {employee.FirstName} and LastName = {employee.LastName} already exists, please create another employee";
                    return View();
                }
                //add employee
                Employee newEmployee = _employeeRepository.Add(employee);
                return RedirectToAction("Details", new { id = newEmployee.EmployeeId });
            }
            return View();
        }

        //Get Employee Details by employee id 
        [HttpGet]
        public IActionResult Details(int id)
        {
            try
            {
                Employee employee = _employeeRepository.GetEmployeeById(id);
                if (employee == null)
                {
                    ViewBag.ErrorMessage = $"Employee with Id = {id} not found.";
                    return View("EmployeeNotFound", id);
                }

                List<Dependent> dependents = _dependentRepository.GetDependentsByEmployeeId(id);
                EmployeeDetailsViewModel employeDetailsViewModel = new EmployeeDetailsViewModel()
                {
                    Employee = employee,
                    Dependents = dependents?.OrderBy(x => x.RelationToEmployee)?.ToList(),
                    PageTitle = "Employee Details",
                    FullName = employee.FirstName + " " + employee.LastName
                };
                return View(employeDetailsViewModel);
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Error");
            }

        }

        //Delete employee by Id
        [HttpPost]
        [ValidateAntiForgeryToken()]
        public IActionResult Delete(int id)
        {
            try
            {
                Employee currentEmployee = _employeeRepository.GetEmployeeById(id);
                if (currentEmployee != null)
                {
                    //get all the dependents for the employee id
                    List<Dependent> dependents = _dependentRepository.GetDependentsByEmployeeId(id);
                    if (dependents.Any())
                    {
                        //loop through and delete all the dependents before deleting the employee
                        foreach (var dependent in dependents)
                        {
                            //delete dependent
                            _dependentRepository?.DeleteDependent(dependent.DependentId);
                        }
                    }
                    //delete employee
                    _employeeRepository?.Delete(currentEmployee.EmployeeId);
                }
                return RedirectToAction("EmployeeList");
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Error");
            }
        }

        //Pay preview method based on employee id
        [HttpGet]
        public IActionResult PayPreview(int id)
        {
            try
            {
                //Get employee by Id
                Employee employee = _employeeRepository.GetEmployeeById(id);
                if (employee == null)
                {
                    ViewBag.ErrorMessage = $"Employee with Id = {id} not found.";
                    return View("EmployeeNotFound", id);
                }

                //Get list of dependents by employee id
                List<Dependent> dependents = _dependentRepository.GetDependentsByEmployeeId(id);

                //Calculate employee and dependent deductions
                CalculateDeductions employeeDeductions = new CalculateDeductions
                {
                    Employee = employee,
                    Dependents = dependents?.OrderBy(x => x.RelationToEmployee)?.ToList(),
                    DependentCount = dependents.Any() ? dependents.Count() : 0,
                    YearlyGrossWages = General.EmployeeStaticData.Employee_Gross_Wages
                    * General.EmployeeStaticData.Pay_Periods_Per_Year,
                    TotalDeductions = Math.Round((EmployeeDeductions(employee) + DependentDeductions(dependents)) / General.EmployeeStaticData.Pay_Periods_Per_Year, 2),
                    EmployeeDeduction = Math.Round(EmployeeDeductions(employee) / General.EmployeeStaticData.Pay_Periods_Per_Year, 2),
                    DependentsDeduction = Math.Round(DependentDeductions(dependents) / General.EmployeeStaticData.Pay_Periods_Per_Year, 2),
                    YearlyTotalDeductions = EmployeeDeductions(employee) + DependentDeductions(dependents),
                    YearlyEmployeeDeduction = EmployeeDeductions(employee),
                    YearlyDependentsDeduction = DependentDeductions(dependents)
                };
                employeeDeductions.YearlyNetWages = employeeDeductions.YearlyGrossWages - employeeDeductions.YearlyTotalDeductions;
                employeeDeductions.GrossWages = General.EmployeeStaticData.Employee_Gross_Wages;
                employeeDeductions.NetWages = employeeDeductions.GrossWages - employeeDeductions.TotalDeductions;
                employeeDeductions.YearlyNetWages = Math.Round(employeeDeductions.YearlyNetWages, 2);
                employeeDeductions.NetWages = Math.Round(employeeDeductions.NetWages, 2);

                return View(employeeDeductions);
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Error");
            }
        }

        //Method to check Name start's with A to apply discount
        private bool IsDiscountAvailable(string firstName)
        {
            //check first name is not null/empty and name starts with 'A'
            if (!string.IsNullOrWhiteSpace(firstName) && firstName.Trim().ToUpper().StartsWith('A'))
                return true;
            return false;
        }

        //Method to retrive employee deductions
        private double EmployeeDeductions(Employee employee)
        {
            //check employee is not null
            if (employee != null && IsDiscountAvailable(employee.FirstName))
            {
                double discount = General.EmployeeStaticData.Employee_Deductions / General.EmployeeStaticData.Deductions_Discount;
                Math.Round(discount, 2);
                return General.EmployeeStaticData.Employee_Deductions - discount;
            }
            return General.EmployeeStaticData.Employee_Deductions;
        }

        //Method to retrive all dependent deductions
        private double DependentDeductions(List<Dependent> dependents)
        {
            //check any dependent's available or not
            if (dependents.Any())
            {
                //get total dependent deductions before discount
                double totalDependentDeductions = dependents.Count() * General.EmployeeStaticData.Dependent_Deductions;
                foreach (var dependent in dependents)
                {
                    //check name start with 'A' or not
                    if (IsDiscountAvailable(dependent.FirstName))
                    {

Code-Challenge/Views/Employee/Create.cshtml
@model Employee

@{
    ViewBag.Title = "Create Employee";
    ViewBag.Header = "Create Employee";

}

@if (ViewBag.ErrorMessage != null)
{
    <h5 class="alert alert-danger">@ViewBag.ErrorMessage</h5>
}

<br />
<h3 style="color: orangered;">Create Employee</h3>

<form asp-controller="Employee" asp-action="Create" method="post" class="mt-3">
    <div class="form-group row">
        <label asp-for="FirstName" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="FirstName" class="form-control" placeholder="First Name" />
            <span asp-validation-for="FirstName" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="LastName" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="LastName" class="form-control" placeholder="Last Name" />
            <span asp-validation-for="LastName" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group row">
        <div class="col-sm-10">
            <button type="submit" class="btn btn-secondary">Create</button>
        </div>
    </div>
</form>

Code-Challenge/Views/Employee/Details.cshtml
@model EmployeeDetailsViewModel

@{
    ViewBag.Title = "Employee Details";
    ViewBag.Header = "Employee Details";
}

<div class="row justify-content-center m-3">
    <div class="col-sm-12">
        <div class="card">
            <div class="card-header">
                <h2>@Model.FullName</h2>
            </div>

            <div class="card-body text-center">
                <h5>Employee ID : @Model.Employee.EmployeeId</h5>
                <h5>Employee Name: @Model.FullName</h5>

                @if (Model.Dependents.Any())
                {
                    <h4 style="color: lightseagreen;">Dependent information</h4>
                    var i = 1; var j = 1; var k = 1;
                    foreach (var dependent in Model.Dependents)
                    {
                        <div class="row">
                            <div class="col-sm-8 p-1">
                                @if (dependent.RelationToEmployee == RelationToEmployee.Spouse)
                                {
                                    <h5>Spouse #@i: @dependent.FirstName @dependent.LastName</h5>
                                    i = i + 1;
                                }
                                else if (dependent.RelationToEmployee == RelationToEmployee.Children)
                                {
                                    <h5>Children #@j: @dependent.FirstName @dependent.LastName</h5>
                                    j = j + 1;
                                }
                                else
                                {
                                    <h5>Unknown #@k: @dependent.FirstName @dependent.LastName</h5>
                                    k = k + 1;
                                }
                            </div>
                            <div class="col-sm-1 p-1">
                                <a asp-action="EditDependent" asp-controller="Dependent"
                                   asp-route-id="@dependent.DependentId" class="btn btn-link">Edit</a>
                            </div>
                            <div class="col-sm-1 p-1">
                                <form asp-controller="Dependent" asp-action="DeleteDependent" asp-route-id="@dependent.DependentId" method="post">
                                    <span id="confirmDeleteSpan_@dependent.DependentId" style="display:none">
                                        <span>Are you sure you want to delete?</span>
                                        <button type="submit" class="btn btn-danger">Yes</button>
                                        <a href="#" class="btn btn-secondary" onclick="confirmDelete('@dependent.DependentId', false)">No</a>
                                    </span>
                                    <span id="deleteSpan_@dependent.DependentId">
                                        <a href="#" class="btn btn-link" onclick="confirmDelete('@dependent.DependentId', true)">Delete</a>
                                    </span>
                                </form>
                            </div>
                        </div>

                    }
                }
                else
                {
                    <h5 style="color: lightseagreen;">No Dependents to display</h5>
                }
            </div>

            <div class="card-body text-center">
                <button type="button" class="btn btn-secondary" style="width:auto" data-toggle="modal" data-target="#addDependentModal">
                    Add Dependent
                </button>
            </div>

            <div class="modal fade" id="addDependentModal" tabindex="-1" role="dialog" aria-labelledby="addDependentModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <form method="post" asp-controller="Dependent" asp-action="AddDependent">
                            <input asp-for="Dependent.EmployeeId" type="hidden" value="@Model.Employee.EmployeeId" />
                            <div class="modal-header">
                                <h5 class="modal-title" id="addDependentModalLabel" style="color: orangered;">Add Dependent</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <div class="form-group">
                                    <label>First Name</label>
                                    <input asp-for="Dependent.FirstName" required="required" class="form-control" placeholder="First Name" />
                                </div>
                                <div class="form-group">
                                    <label>Last Name</label>
                                    <input asp-for="Dependent.LastName" required="required" class="form-control" placeholder="Last Name" />
                                </div>
                                <div class="form-group">
                                    <label>Relationship</label>
                                    <select required="required" asp-for="Dependent.RelationToEmployee" class="form-control"
                                            asp-items="Html.GetEnumSelectList<RelationToEmployee>()">
                                        <option value="">Please Select</option>
                                    </select>
                                </div>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                <button type="submit" class="btn btn-secondary" style="width:auto">Add Dependent</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>

            <div class="card-footer text-center">
                <a asp-controller="employee" asp-action="EmployeeList"
                   class="btn btn-secondary">Back</a> &nbsp; &nbsp; &nbsp;
                <a asp-controller="employee" asp-action="PayPreview" asp-route-id="@Model.Employee.EmployeeId"
                   class="btn btn-secondary" style="width:auto">Pay Preview</a>
            </div>
        </div>
    </div>

</div>

@section Scripts{
    <script src="~/js/CustomScript.js"></script>
}

Code-Challenge/Views/Employee/EmployeeList.cshtml
@model EmployeesListViewModel

@{
    ViewBag.Title = "Employee List";
    ViewBag.Header = "Employee List";
}

<br />
<form method="get" asp-controller="Employee" asp-action="search">
    <div class="input-group">
        <input class="form-control" asp-for="SearchTerm" />
        <div class="input-group-append">
            <button type="submit" class="btn btn-secondary">Search</button>
        </div>
    </div>
</form>

<br />
<a asp-controller="Employee" asp-action="Create" class="btn btn-secondary" style="width:auto;">Create Employee</a>

<div class="card-deck">
    @if (Model.Employees.Any())
    {
        foreach (var employee in Model.Employees)
        {
            <div class="card m-3">
                <div class="card-header">
                    <h3>@employee.FirstName @employee.LastName</h3>
                </div>
                <div class="card-footer text-center">
                    <form asp-controller="Employee" asp-action="delete" asp-route-id="@employee.EmployeeId" method="post">
                        <a asp-controller="Employee" asp-action="details" asp-route-id="@employee.EmployeeId"
                           class="btn btn-secondary m-1">View</a>
                        <span id="confirmDeleteSpan_@employee.EmployeeId" style="display:none">
                            <span>Are you sure you want to delete?</span>
                            <button type="submit" class="btn btn-danger">Yes</button>
                            <a href="#" class="btn btn-secondary" onclick="confirmDelete('@employee.EmployeeId', false)">No</a>
                        </span>
                        <span id="deleteSpan_@employee.EmployeeId">
                            <a href="#" class="btn btn-danger m-1" onclick="confirmDelete('@employee.EmployeeId', true)">Delete</a>
                        </span>
                    </form>
                </div>
            </div>
        }
    }
    else
    {
        <h2 class="m-3">No Employees to display</h2>
    }

</div>

@section Scripts {
    <script src="~/js/CustomScript.js"></script>
}

Code-Challenge/Views/Employee/EmployeeNotFound.cshtml
@model int 

@{ 
    ViewBag.Title = "404 Error";
} 

<div class="alert alert-danger mt-1 mb-1">
    <h4>404 Not Found Error : </h4>
    <hr />
    <h5>
        Employee with Id = @Model cannot be found
    </h5>
</div>

<a asp-action="EmployeeList" asp-controller="Employee" class="btn btn btn-outline-success" style="width:auto">
    Click here to see the list of all employees
</a>

Code-Challenge/Views/Employee/PayPreview.cshtml
@model CalculateDeductions

@{
    ViewBag.Title = "Pay Check Preview";
    ViewBag.Header = "Pay Check Preview";
}

<div class="row justify-content-center m-3">
    <div class="col-sm-12">
        <div class="card">
            <div class="card-header">
                <h2 class="float-left">@Model.Employee.FirstName @Model.Employee.LastName</h2>
                <h6 class="float-right">Date:  @DateTime.Now.ToString("MMMM dd, yyyy")</h6>
            </div>

            <div class="card-body text-center">
                <h4 style="color: orangered;">Employee Pay Preview</h4>
                <div class="table table-striped">
                    <h5 style="color: lightseagreen;">Employee Information</h5>
                    <table style="width:100%">
                        <tr>
                            <td style="width:50%">Employee ID</td>
                            <td>@Model.Employee.EmployeeId</td>
                        </tr>
                        <tr>
                            <td>Employee Name</td>
                            <td>@Model.Employee.FirstName @Model.Employee.LastName</td>
                        </tr>
                        <tr>
                            <td>Employee Deductions</td>
                            <td>$1000 per year</td>
                        </tr>
                        <tr>
                            <td>Dependent Deductions</td>
                            <td>$500 per year per each dependent</td>
                        </tr>
                        @if (Model.Dependents.Any())
                        {
                            foreach (var dependent in Model.Dependents)
                            {
                                if (dependent.RelationToEmployee == RelationToEmployee.Spouse)
                                {
                                    <tr>
                                        <td>Spouse Name</td>
                                        <td>@dependent.FirstName @dependent.LastName</td>
                                    </tr>
                                }
                                else
                                {
                                    <tr>
                                        <td>Children Name</td>
                                        <td>@dependent.FirstName @dependent.LastName</td>
                                    </tr>
                                }
                            }
                        }
                        <tr></tr>
                    </table>
                </div>

                <div class="table table-striped">
                    <h5 style="color: lightseagreen;">Per Pay Check Earnings</h5>
                    <table style="width:100%">
                        <tr>
                            <td style="width:50%">Gross Earnings</td>
                            <td>$@Model.GrossWages</td>
                        </tr>
                        <tr>
                            <td>Pay Frequency</td>
                            <td>Biweekly</td>
                        </tr>
                        <tr>
                            <td>Employee Deductions</td>
                            <td>$@Model.EmployeeDeduction</td>
                        </tr>
                        <tr>
                            <td>No. of Dependents</td>
                            <td>@Model.DependentCount</td>
                        </tr>
                        <tr>
                            <td>Dependent Deductions</td>
                            <td>$@Model.DependentsDeduction</td>
                        </tr>
                        <tr>
                            <td>Total Deductions</td>
                            <td>$@Model.TotalDeductions</td>
                        </tr>
                        <tr>
                            <td>Net Earnings</td>
                            <td>$@Model.NetWages</td>
                        </tr>
                    </table>
                </div>
                <div class="table table-striped">
                    <h5 style="color: lightseagreen;">Yearly Earnings</h5>
                    <table style="width:100%">
                        <tr>
                            <td style="width:50%">Gross Earnings</td>
                            <td>$@Model.YearlyGrossWages</td>
                        </tr>
                        <tr>
                            <td>Employee Deductions</td>
                            <td>$@Model.YearlyEmployeeDeduction</td>
                        </tr>
                        <tr>
                            <td>No. of Dependents</td>
                            <td>@Model.DependentCount</td>
                        </tr>
                        <tr>
                            <td>Dependent Deductions</td>
                            <td>$@Model.YearlyDependentsDeduction</td>
                        </tr>
                        <tr>
                            <td>Total Deductions</td>
                            <td>$@Model.YearlyTotalDeductions</td>
                        </tr>
                        <tr>
                            <td>Net Earnings</td>
                            <td>$@Model.YearlyNetWages</td>
                        </tr>
                    </table>
                </div>
            </div>

            <div class="card-footer text-center">
                <a asp-controller="Employee" asp-action="Details"
                   asp-route-id="@Model.Employee.EmployeeId" class="btn btn-secondary">Back</a>
            </div>
        </div>
    </div>

</div>